Repository CityOfBoston/digital, pull requests merged in 2019-05, with the labels that each got.

#434 Adds text instructions; fixes #371
  modules-js/react-fleet/src/utilities/css.ts
  services-js/registry-certs/client/__snapshots__/Storyshots.test.ts.snap
  services-js/registry-certs/client/birth/ReviewRequestPage.tsx
  services-js/registry-certs/client/birth/components/ApostilleRequestInstructions.tsx
Labels: registry-certs

#436 Upgrades to Emotion 10
  modules-js/form-common/package.json
  modules-js/react-fleet/package.json
  modules-js/react-fleet/src/form-elements/inputs/MemorableDateInput.tsx
  modules-js/react-fleet/src/navigation/BreadcrumbNav.tsx
  services-js/311/package.json
  services-js/311/pages/_app.tsx
  services-js/access-boston/package.json
  services-js/access-boston/src/pages/_app.tsx
  services-js/commissions-app/package.json
  services-js/commissions-app/src/client/ApplicationForm.tsx
  services-js/commissions-app/src/pages/_app.tsx
  services-js/public-notices/package.json
  services-js/public-notices/src/__snapshots__/Storyshots.test.ts.snap
  services-js/public-notices/src/components/NoticeDetail.tsx
  services-js/public-notices/src/components/PublicNoticesContent.tsx
  services-js/public-notices/src/pages/_app.tsx
  services-js/registry-certs/client/__snapshots__/Storyshots.test.ts.snap
  services-js/registry-certs/client/birth/components/QuantityDropdown.tsx
  services-js/registry-certs/package.json
  services-js/registry-certs/pages/_app.tsx
  templates/js-browser-module/template/package.json
  yarn.lock
Labels: tech debt

#437 Migrates react-fleet to Emotion css prop
  .eslintrc
  modules-js/config-babel/package.json
  modules-js/form-common/package.json
  modules-js/react-fleet/.storybook/.babelrc
  modules-js/react-fleet/package.json
  modules-js/react-fleet/rollup.config.js
  modules-js/react-fleet/src/__snapshots__/Storyshots.test.ts.snap
  modules-js/react-fleet/src/components/ProgressBar.tsx
  modules-js/react-fleet/src/components/StatusModal.tsx
  modules-js/react-fleet/src/form-elements/UploadPhoto.stories.tsx
  modules-js/react-fleet/src/form-elements/UploadPhoto.tsx
  modules-js/react-fleet/src/form-elements/buttons/CloseButton.tsx
  modules-js/react-fleet/src/form-elements/inputs/FileInput.tsx
  modules-js/react-fleet/src/form-elements/inputs/MemorableDateInput.tsx
  modules-js/react-fleet/src/navigation/BreadcrumbNav.tsx
  modules-js/react-fleet/src/sectioning-elements/CollapsibleSection.tsx
  modules-js/react-fleet/src/utilities/css.ts
  package.json
  services-js/commissions-app/src/stories/__snapshots__/Storyshots.test.ts.snap
  services-js/registry-certs/client/__snapshots__/Storyshots.test.ts.snap
  services-js/registry-certs/client/birth/components/ApostilleRequestInstructions.tsx
  services-js/registry-certs/client/birth/components/RadioItemComponent.tsx
  services-js/registry-certs/client/birth/components/SupportingDocumentsInput.tsx
  services-js/registry-certs/client/common/CostSummary.tsx
  yarn.lock
Labels: tech debt

#438 Eliminates warnings in Jest runs
  services-js/311/.storybook/__snapshots__/Storyshots.test.ts.snap
  services-js/311/components/request/RequestLayout.test.tsx
  services-js/311/components/request/home/__snapshots__/HomeDialog.test.tsx.snap
  services-js/311/components/request/request/__snapshots__/RequestDialog.test.tsx.snap
  services-js/payment-webhooks/server/stripe-events.ts
  services-js/registry-certs/client/__snapshots__/Storyshots.test.ts.snap
  services-js/registry-certs/client/birth/QuestionsPage.stories.tsx
  services-js/registry-certs/client/birth/QuestionsPage.tsx
  services-js/registry-certs/client/birth/ReviewRequestPage.stories.tsx
  services-js/registry-certs/client/birth/ReviewRequestPage.tsx
  services-js/registry-certs/client/birth/components/SupportingDocumentsInput.stories.tsx
  services-js/registry-certs/client/common/checkout/formik-util.ts
  yarn.lock
Labels: tech debt

#439 Upgrades Jest to 24.8
  deploy-tools.tgz
  modules-js/deploy-tools/package.json
  modules-js/form-common/package.json
  modules-js/graphql-typescript/package.json
  modules-js/hapi-common/package.json
  modules-js/hapi-next/package.json
  modules-js/mssql-common/package.json
  modules-js/next-client-common/package.json
  modules-js/percy-common/package.json
  modules-js/react-fleet/package.json
  modules-js/srv-decrypt-env/package.json
  modules-js/storybook-common/package.json
  package.json
  services-js/311-indexer/package.json
  services-js/311/package.json
  services-js/access-boston/package.json
  services-js/commissions-app/package.json
  services-js/internal-slack-bot/package.json
  services-js/payment-webhooks/package.json
  services-js/public-notices/package.json
  services-js/registry-certs/package.json
  templates/js-browser-module/package.json
  templates/js-browser-module/template/package.json
  templates/js-server-module/package.json
  templates/js-server-module/template/package.json
  yarn.lock
Labels: tech debt

#442 Upgrades GraphQL libraries and tooling
  .travis.yml
  modules-js/hapi-common/package.json
  modules-js/hapi-common/src/hapi-common.test.ts
  modules-js/hapi-common/src/hapi-common.ts
  services-js/311/data/queries/types.ts
  services-js/311/package.json
  services-js/311/server/graphql/index.ts
  services-js/311/server/server.ts
  services-js/access-boston/package.json
  services-js/access-boston/src/client/graphql/queries.ts
  services-js/access-boston/src/server/access-boston.ts
  services-js/access-boston/src/server/graphql/schema.ts
  services-js/commissions-app/package.json
  services-js/commissions-app/src/client/graphql/queries.ts
  services-js/commissions-app/src/server/__snapshots__/commissions-app.test.ts.snap
  services-js/commissions-app/src/server/commissions-app.test.ts
  services-js/commissions-app/src/server/commissions-app.ts
  services-js/commissions-app/src/server/graphql/schema.ts
  services-js/commissions-search/package.json
  services-js/registry-certs/client/queries/graphql-types.ts
  services-js/registry-certs/package.json
  services-js/registry-certs/server/__snapshots__/server.test.ts.snap
  services-js/registry-certs/server/graphql/__snapshots__/index.test.js.snap
  services-js/registry-certs/server/graphql/index.ts
  services-js/registry-certs/server/graphql/mutation.ts
  services-js/registry-certs/server/queries/fulfillment/README.md
  services-js/registry-certs/server/queries/fulfillment/request-bc-documentation-v1.graphql
  services-js/registry-certs/server/server.test.ts
  services-js/registry-certs/server/server.ts
  services-js/registry-certs/server/services/RegistryDb.ts
  yarn.lock
Labels: tech debt

#443 Adds new URL to the portal
  services-js/access-boston/README.md
  services-js/access-boston/fixtures/apps.yaml
  services-js/access-boston/src/stories/__snapshots__/Storyshots.test.ts.snap
Labels: access-boston

#444 Upgrades TypeScript from 3.4.4 -> 3.4.5
  deploy-tools.tgz
  modules-js/config-typescript/README.md
  modules-js/deploy-tools/package.json
  modules-js/form-common/package.json
  modules-js/graphql-typescript/package.json
  modules-js/hapi-common/package.json
  modules-js/hapi-next/package.json
  modules-js/mssql-common/package.json
  modules-js/mssql-typescript/package.json
  modules-js/next-client-common/package.json
  modules-js/percy-common/package.json
  modules-js/react-fleet/package.json
  modules-js/srv-decrypt-env/package.json
  modules-js/storybook-common/package.json
  package.json
  services-js/311-indexer/package.json
  services-js/311/package.json
  services-js/access-boston/package.json
  services-js/commissions-app/package.json
  services-js/internal-slack-bot/package.json
  services-js/payment-webhooks/package.json
  services-js/public-notices/package.json
  services-js/registry-certs/package.json
  templates/js-browser-module/package.json
  templates/js-browser-module/template/package.json
  templates/js-server-module/package.json
  templates/js-server-module/template/package.json
  yarn.lock
Labels: tech debt

#446 Upgrades Next from 8 -> 8.1
  modules-js/config-babel/package.json
  modules-js/hapi-next/package.json
  modules-js/next-client-common/package.json
  services-js/311/components/request/request/__snapshots__/RequestDialog.test.tsx.snap
  services-js/311/components/style-constants.ts
  services-js/311/package.json
  services-js/access-boston/package.json
  services-js/commissions-app/package.json
  services-js/public-notices/package.json
  services-js/registry-certs/package.json
  yarn.lock
Labels: tech debt

#453 Next canary prep
  modules-js/config-typescript/tsconfig.default.json
  modules-js/hapi-next/src/hapi-next.ts
  modules-js/next-client-common/src/RouterListener.ts
  modules-js/next-client-common/src/next-client-common.test.ts
  modules-js/next-client-common/src/next-client-common.ts
  services-js/311/components/case/CaseLayout.tsx
  services-js/311/components/request/home/HomeDialog.tsx
  services-js/311/components/request/request/RequestDialog.tsx
  services-js/311/components/search/SearchLayout.tsx
  services-js/311/pages/_app.tsx
  services-js/access-boston/src/pages/_app.tsx
  services-js/access-boston/src/pages/change-password.tsx
  services-js/access-boston/src/server/access-boston.ts
  services-js/commissions-app/src/pages/commissions/apply.tsx
  services-js/commissions-app/src/server/commissions-app.ts
  services-js/registry-certs/client/birth/CheckoutPage.tsx
  services-js/registry-certs/client/death/certificate/CertificatePage.tsx
  services-js/registry-certs/client/death/certificate/__snapshots__/CertificatePage.test.tsx.snap
  services-js/registry-certs/client/death/checkout/CheckoutPage.tsx
  services-js/registry-certs/client/death/receipt/ReceiptPage.tsx
  services-js/registry-certs/client/death/search/SearchPage.tsx
  services-js/registry-certs/pages/_app.tsx
  services-js/registry-certs/server/server.ts
Labels: tech debt

#455 Marriage Certs prep: emails
  services-js/registry-certs/client/__snapshots__/Storyshots.test.ts.snap
  services-js/registry-certs/client/common/checkout/OrderConfirmationContent.tsx
  services-js/registry-certs/client/marriage/CheckoutPage.tsx
  services-js/registry-certs/client/marriage/QuestionsPage.tsx
  services-js/registry-certs/client/marriage/ReviewRequestPage.tsx
  services-js/registry-certs/server/email/EmailTemplates.stories.tsx
  services-js/registry-certs/server/email/EmailTemplates.test.ts
  services-js/registry-certs/server/email/EmailTemplates.ts
  services-js/registry-certs/server/email/__snapshots__/EmailTemplates.test.ts.snap
  services-js/registry-certs/server/email/expired.mjml.hbs
  services-js/registry-certs/server/email/expired.txt.hbs
  services-js/registry-certs/server/services/Emails.ts
Labels: registry-certs

#457 Fire permit support for Permit Finder
  services-js/internal-slack-bot/Dockerfile
  services-js/permit-finder/package.json
  services-js/permit-finder/src/client/graphql/load-permit.ts
  services-js/permit-finder/src/client/graphql/queries.ts
  services-js/permit-finder/src/pages/permit.tsx
  services-js/permit-finder/src/server/permit-finder.ts
  services-js/permit-finder/src/server/services/PermitFiles.ts
  services-js/permit-finder/src/stories/PermitPage.stories.tsx
  services-js/permit-finder/src/stories/__snapshots__/Storyshots.test.ts.snap
  yarn.lock
Labels: permit-finder

#459 Calls compactRange after deleting keys
  services-js/permit-finder/package.json
  services-js/permit-finder/src/server/services/PermitFiles.ts
  yarn.lock
Labels: permit-finder
